### ISSUE TITLE
Pick a Better Font for Text

### ISSUE THREAD

**Issue by fyy26** [pennapps/2023f.pennapps#15]
Something that isn't hollow

On Figma it's Terminal Grotesque, but anything similar would work

**Comment by fyy26** [comment]
I think it's just with the current font that small text turns hollow. Maybe pick another font that's more readable but also fits the cyber feeling.

**Comment by gumillie222** [comment]
have it resolved! terminal grotesque and not hollow. It's just in the same pr as landing page

**Comment by fyy26** [comment]
Addressed with #26
