### ISSUE TITLE
Make Application title not go out of the box on mobile

### ISSUE THREAD

**Issue by fyy26** [pennapps/2023f.pennapps#69]
<img width="491" alt="image" src="https://github.com/pennapps/2023f.pennapps/assets/54198723/f3a975d2-5ff7-4d73-9c78-63f139400c1d">

**Comment by sidhants25** [comment]
seems to me the issue has been fixed under this branch.

![image](https://github.com/pennapps/2023f.pennapps/assets/106752334/052ce7ee-fc74-4bf5-a63c-e1f49c54c309)
